name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/setup-flutter
     - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
