name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    permissions:
      id-token: write
    uses: ./.github/actions/setup-flutter
    run: dart pub publish --force
    with:
      environment: pub.dev
