name: Pull Request

on: [ pull_request ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-flutter

      - name: Activate melos
        run: dart pub global activate melos 2.7.1

      - name: Get dependencies
        run: melos run pub_get:all

      - name: Verify formatting
        run: melos run verify_format:all --no-select

      - name: Analyze
        run: melos run analyze:all --no-select

      - name: Run Flutter tests
        run: melos run test_flutter:all --no-select

